name: Daily Issue Finder

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests pandas tabulate # tabulate is needed for to_markdown

      - name: Run issue finding script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python find_issues.py

      - name: Update README.md
        run: python update_readme.py

      - name: Commit and push if it changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update daily issues and README"
          file_pattern: "issues.csv README.md" # Watch both files for changes
